set(_CATKIN_CURRENT_PACKAGE "rrbot_description")
set(rrbot_description_VERSION "0.0.0")
set(rrbot_description_MAINTAINER "Dave Coleman <davetcoleman@gmail.com>")
set(rrbot_description_PACKAGE_FORMAT "1")
set(rrbot_description_BUILD_DEPENDS )
set(rrbot_description_BUILD_EXPORT_DEPENDS "joint_state_publisher" "robot_state_publisher" "rviz")
set(rrbot_description_BUILDTOOL_DEPENDS "catkin")
set(rrbot_description_BUILDTOOL_EXPORT_DEPENDS )
set(rrbot_description_EXEC_DEPENDS "joint_state_publisher" "robot_state_publisher" "rviz")
set(rrbot_description_RUN_DEPENDS "joint_state_publisher" "robot_state_publisher" "rviz")
set(rrbot_description_TEST_DEPENDS )
set(rrbot_description_DOC_DEPENDS )
set(rrbot_description_URL_WEBSITE "http://http://gazebosim.org/w/index.php?title=Tutorials/1.9/Using_A_URDF_In_Gazebo")
set(rrbot_description_URL_BUGTRACKER "https://github.com/osrf/gazebo_ros_demos/issues")
set(rrbot_description_URL_REPOSITORY "https://github.com/osrf/gazebo_ros_demos")
set(rrbot_description_DEPRECATED "")