set(_CATKIN_CURRENT_PACKAGE "joint_limits_interface")
set(joint_limits_interface_VERSION "0.19.4")
set(joint_limits_interface_MAINTAINER "Bence Magyar <bence.magyar.robotics@gmail.com>, Enrique Fernandez <enrique.fernandez.perdomo@gmail.com>, Mathias Lüdtke <mathias.luedtke@ipa.fraunhofer.de>")
set(joint_limits_interface_PACKAGE_FORMAT "3")
set(joint_limits_interface_BUILD_DEPENDS "hardware_interface" "roscpp" "urdf")
set(joint_limits_interface_BUILD_EXPORT_DEPENDS "hardware_interface" "roscpp" "urdf")
set(joint_limits_interface_BUILDTOOL_DEPENDS "catkin")
set(joint_limits_interface_BUILDTOOL_EXPORT_DEPENDS )
set(joint_limits_interface_EXEC_DEPENDS "roscpp" "urdf")
set(joint_limits_interface_RUN_DEPENDS "roscpp" "urdf" "hardware_interface")
set(joint_limits_interface_TEST_DEPENDS "rostest")
set(joint_limits_interface_DOC_DEPENDS )
set(joint_limits_interface_URL_WEBSITE "https://github.com/ros-controls/ros_control/wiki")
set(joint_limits_interface_URL_BUGTRACKER "https://github.com/ros-controls/ros_control/issues")
set(joint_limits_interface_URL_REPOSITORY "https://github.com/ros-controls/ros_control")
set(joint_limits_interface_DEPRECATED "")