set(_CATKIN_CURRENT_PACKAGE "gripper_action_controller")
set(gripper_action_controller_VERSION "0.18.1")
set(gripper_action_controller_MAINTAINER "Sachin Chitta <robot.moveit@gmail.com>, Bence Magyar <bence.magyar.robotics@gmail.com>, Enrique Fernandez <enrique.fernandez.perdomo@gmail.com>")
set(gripper_action_controller_PACKAGE_FORMAT "3")
set(gripper_action_controller_BUILD_DEPENDS "control_msgs" "hardware_interface" "pluginlib" "actionlib" "controller_interface" "control_toolbox" "realtime_tools" "roscpp" "urdf")
set(gripper_action_controller_BUILD_EXPORT_DEPENDS "control_msgs" "hardware_interface" "actionlib" "controller_interface" "control_toolbox" "realtime_tools" "roscpp" "urdf")
set(gripper_action_controller_BUILDTOOL_DEPENDS "catkin")
set(gripper_action_controller_BUILDTOOL_EXPORT_DEPENDS )
set(gripper_action_controller_EXEC_DEPENDS "actionlib" "controller_interface" "control_toolbox" "realtime_tools" "roscpp" "urdf")
set(gripper_action_controller_RUN_DEPENDS "actionlib" "controller_interface" "control_toolbox" "realtime_tools" "roscpp" "urdf" "control_msgs" "hardware_interface")
set(gripper_action_controller_TEST_DEPENDS )
set(gripper_action_controller_DOC_DEPENDS )
set(gripper_action_controller_URL_WEBSITE "")
set(gripper_action_controller_URL_BUGTRACKER "")
set(gripper_action_controller_URL_REPOSITORY "")
set(gripper_action_controller_DEPRECATED "")