set(_CATKIN_CURRENT_PACKAGE "combined_robot_hw")
set(combined_robot_hw_VERSION "0.19.4")
set(combined_robot_hw_MAINTAINER "Bence Magyar <bence.magyar.robotics@gmail.com>, Toni Oliver <toni@shadowrobot.com>, Enrique Fernandez <enrique.fernandez.perdomo@gmail.com>, Mathias Lüdtke <mathias.luedtke@ipa.fraunhofer.de>")
set(combined_robot_hw_PACKAGE_FORMAT "3")
set(combined_robot_hw_BUILD_DEPENDS "hardware_interface" "pluginlib" "roscpp")
set(combined_robot_hw_BUILD_EXPORT_DEPENDS "hardware_interface" "pluginlib" "roscpp")
set(combined_robot_hw_BUILDTOOL_DEPENDS "catkin")
set(combined_robot_hw_BUILDTOOL_EXPORT_DEPENDS )
set(combined_robot_hw_EXEC_DEPENDS "roscpp")
set(combined_robot_hw_RUN_DEPENDS "roscpp" "hardware_interface" "pluginlib")
set(combined_robot_hw_TEST_DEPENDS )
set(combined_robot_hw_DOC_DEPENDS )
set(combined_robot_hw_URL_WEBSITE "https://github.com/ros-controls/ros_control/wiki")
set(combined_robot_hw_URL_BUGTRACKER "https://github.com/ros-controls/ros_control/issues")
set(combined_robot_hw_URL_REPOSITORY "https://github.com/ros-controls/ros_control")
set(combined_robot_hw_DEPRECATED "")