set(_CATKIN_CURRENT_PACKAGE "controller_manager_msgs")
set(controller_manager_msgs_VERSION "0.19.4")
set(controller_manager_msgs_MAINTAINER "Bence Magyar <bence.magyar.robotics@gmail.com>, Enrique Fernandez <enrique.fernandez.perdomo@gmail.com>, Mathias Lüdtke <mathias.luedtke@ipa.fraunhofer.de>")
set(controller_manager_msgs_PACKAGE_FORMAT "3")
set(controller_manager_msgs_BUILD_DEPENDS "message_generation" "std_msgs")
set(controller_manager_msgs_BUILD_EXPORT_DEPENDS "std_msgs")
set(controller_manager_msgs_BUILDTOOL_DEPENDS "catkin" "python-setuptools" "python3-setuptools")
set(controller_manager_msgs_BUILDTOOL_EXPORT_DEPENDS )
set(controller_manager_msgs_EXEC_DEPENDS "message_runtime" "rosservice" "rospy" "std_msgs")
set(controller_manager_msgs_RUN_DEPENDS "message_runtime" "rosservice" "rospy" "std_msgs")
set(controller_manager_msgs_TEST_DEPENDS )
set(controller_manager_msgs_DOC_DEPENDS )
set(controller_manager_msgs_URL_WEBSITE "https://github.com/ros-controls/ros_control/wiki")
set(controller_manager_msgs_URL_BUGTRACKER "https://github.com/ros-controls/ros_control/issues")
set(controller_manager_msgs_URL_REPOSITORY "https://github.com/ros-controls/ros_control")
set(controller_manager_msgs_DEPRECATED "")