# CMake generated Testfile for 
# Source directory: /home/akingse/tempopkg_ws/src/ros_control/transmission_interface
# Build directory: /home/akingse/tempopkg_ws/build_isolated/transmission_interface
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(_ctest_transmission_interface_gtest_simple_transmission_test "/home/akingse/tempopkg_ws/build_isolated/transmission_interface/catkin_generated/env_cached.sh" "/usr/bin/python2" "/opt/ros/kinetic/share/catkin/cmake/test/run_tests.py" "/home/akingse/tempopkg_ws/build_isolated/transmission_interface/test_results/transmission_interface/gtest-simple_transmission_test.xml" "--return-code" "/home/akingse/tempopkg_ws/devel_isolated/transmission_interface/lib/transmission_interface/simple_transmission_test --gtest_output=xml:/home/akingse/tempopkg_ws/build_isolated/transmission_interface/test_results/transmission_interface/gtest-simple_transmission_test.xml")
set_tests_properties(_ctest_transmission_interface_gtest_simple_transmission_test PROPERTIES  _BACKTRACE_TRIPLES "/opt/ros/kinetic/share/catkin/cmake/test/tests.cmake;160;add_test;/opt/ros/kinetic/share/catkin/cmake/test/gtest.cmake;98;catkin_run_tests_target;/opt/ros/kinetic/share/catkin/cmake/test/gtest.cmake;37;_catkin_add_google_test;/home/akingse/tempopkg_ws/src/ros_control/transmission_interface/CMakeLists.txt;93;catkin_add_gtest;/home/akingse/tempopkg_ws/src/ros_control/transmission_interface/CMakeLists.txt;0;")
add_test(_ctest_transmission_interface_gtest_differential_transmission_test "/home/akingse/tempopkg_ws/build_isolated/transmission_interface/catkin_generated/env_cached.sh" "/usr/bin/python2" "/opt/ros/kinetic/share/catkin/cmake/test/run_tests.py" "/home/akingse/tempopkg_ws/build_isolated/transmission_interface/test_results/transmission_interface/gtest-differential_transmission_test.xml" "--return-code" "/home/akingse/tempopkg_ws/devel_isolated/transmission_interface/lib/transmission_interface/differential_transmission_test --gtest_output=xml:/home/akingse/tempopkg_ws/build_isolated/transmission_interface/test_results/transmission_interface/gtest-differential_transmission_test.xml")
set_tests_properties(_ctest_transmission_interface_gtest_differential_transmission_test PROPERTIES  _BACKTRACE_TRIPLES "/opt/ros/kinetic/share/catkin/cmake/test/tests.cmake;160;add_test;/opt/ros/kinetic/share/catkin/cmake/test/gtest.cmake;98;catkin_run_tests_target;/opt/ros/kinetic/share/catkin/cmake/test/gtest.cmake;37;_catkin_add_google_test;/home/akingse/tempopkg_ws/src/ros_control/transmission_interface/CMakeLists.txt;95;catkin_add_gtest;/home/akingse/tempopkg_ws/src/ros_control/transmission_interface/CMakeLists.txt;0;")
add_test(_ctest_transmission_interface_gtest_four_bar_linkage_transmission_test "/home/akingse/tempopkg_ws/build_isolated/transmission_interface/catkin_generated/env_cached.sh" "/usr/bin/python2" "/opt/ros/kinetic/share/catkin/cmake/test/run_tests.py" "/home/akingse/tempopkg_ws/build_isolated/transmission_interface/test_results/transmission_interface/gtest-four_bar_linkage_transmission_test.xml" "--return-code" "/home/akingse/tempopkg_ws/devel_isolated/transmission_interface/lib/transmission_interface/four_bar_linkage_transmission_test --gtest_output=xml:/home/akingse/tempopkg_ws/build_isolated/transmission_interface/test_results/transmission_interface/gtest-four_bar_linkage_transmission_test.xml")
set_tests_properties(_ctest_transmission_interface_gtest_four_bar_linkage_transmission_test PROPERTIES  _BACKTRACE_TRIPLES "/opt/ros/kinetic/share/catkin/cmake/test/tests.cmake;160;add_test;/opt/ros/kinetic/share/catkin/cmake/test/gtest.cmake;98;catkin_run_tests_target;/opt/ros/kinetic/share/catkin/cmake/test/gtest.cmake;37;_catkin_add_google_test;/home/akingse/tempopkg_ws/src/ros_control/transmission_interface/CMakeLists.txt;97;catkin_add_gtest;/home/akingse/tempopkg_ws/src/ros_control/transmission_interface/CMakeLists.txt;0;")
add_test(_ctest_transmission_interface_gtest_transmission_interface_test "/home/akingse/tempopkg_ws/build_isolated/transmission_interface/catkin_generated/env_cached.sh" "/usr/bin/python2" "/opt/ros/kinetic/share/catkin/cmake/test/run_tests.py" "/home/akingse/tempopkg_ws/build_isolated/transmission_interface/test_results/transmission_interface/gtest-transmission_interface_test.xml" "--return-code" "/home/akingse/tempopkg_ws/devel_isolated/transmission_interface/lib/transmission_interface/transmission_interface_test --gtest_output=xml:/home/akingse/tempopkg_ws/build_isolated/transmission_interface/test_results/transmission_interface/gtest-transmission_interface_test.xml")
set_tests_properties(_ctest_transmission_interface_gtest_transmission_interface_test PROPERTIES  _BACKTRACE_TRIPLES "/opt/ros/kinetic/share/catkin/cmake/test/tests.cmake;160;add_test;/opt/ros/kinetic/share/catkin/cmake/test/gtest.cmake;98;catkin_run_tests_target;/opt/ros/kinetic/share/catkin/cmake/test/gtest.cmake;37;_catkin_add_google_test;/home/akingse/tempopkg_ws/src/ros_control/transmission_interface/CMakeLists.txt;99;catkin_add_gtest;/home/akingse/tempopkg_ws/src/ros_control/transmission_interface/CMakeLists.txt;0;")
add_test(_ctest_transmission_interface_gtest_transmission_parser_test "/home/akingse/tempopkg_ws/build_isolated/transmission_interface/catkin_generated/env_cached.sh" "/usr/bin/python2" "/opt/ros/kinetic/share/catkin/cmake/test/run_tests.py" "/home/akingse/tempopkg_ws/build_isolated/transmission_interface/test_results/transmission_interface/gtest-transmission_parser_test.xml" "--return-code" "/home/akingse/tempopkg_ws/devel_isolated/transmission_interface/lib/transmission_interface/transmission_parser_test --gtest_output=xml:/home/akingse/tempopkg_ws/build_isolated/transmission_interface/test_results/transmission_interface/gtest-transmission_parser_test.xml")
set_tests_properties(_ctest_transmission_interface_gtest_transmission_parser_test PROPERTIES  _BACKTRACE_TRIPLES "/opt/ros/kinetic/share/catkin/cmake/test/tests.cmake;160;add_test;/opt/ros/kinetic/share/catkin/cmake/test/gtest.cmake;98;catkin_run_tests_target;/opt/ros/kinetic/share/catkin/cmake/test/gtest.cmake;37;_catkin_add_google_test;/home/akingse/tempopkg_ws/src/ros_control/transmission_interface/CMakeLists.txt;102;catkin_add_gtest;/home/akingse/tempopkg_ws/src/ros_control/transmission_interface/CMakeLists.txt;0;")
add_test(_ctest_transmission_interface_gtest_simple_transmission_loader_test "/home/akingse/tempopkg_ws/build_isolated/transmission_interface/catkin_generated/env_cached.sh" "/usr/bin/python2" "/opt/ros/kinetic/share/catkin/cmake/test/run_tests.py" "/home/akingse/tempopkg_ws/build_isolated/transmission_interface/test_results/transmission_interface/gtest-simple_transmission_loader_test.xml" "--return-code" "/home/akingse/tempopkg_ws/devel_isolated/transmission_interface/lib/transmission_interface/simple_transmission_loader_test --gtest_output=xml:/home/akingse/tempopkg_ws/build_isolated/transmission_interface/test_results/transmission_interface/gtest-simple_transmission_loader_test.xml")
set_tests_properties(_ctest_transmission_interface_gtest_simple_transmission_loader_test PROPERTIES  _BACKTRACE_TRIPLES "/opt/ros/kinetic/share/catkin/cmake/test/tests.cmake;160;add_test;/opt/ros/kinetic/share/catkin/cmake/test/gtest.cmake;98;catkin_run_tests_target;/opt/ros/kinetic/share/catkin/cmake/test/gtest.cmake;37;_catkin_add_google_test;/home/akingse/tempopkg_ws/src/ros_control/transmission_interface/CMakeLists.txt;105;catkin_add_gtest;/home/akingse/tempopkg_ws/src/ros_control/transmission_interface/CMakeLists.txt;0;")
add_test(_ctest_transmission_interface_gtest_differential_transmission_loader_test "/home/akingse/tempopkg_ws/build_isolated/transmission_interface/catkin_generated/env_cached.sh" "/usr/bin/python2" "/opt/ros/kinetic/share/catkin/cmake/test/run_tests.py" "/home/akingse/tempopkg_ws/build_isolated/transmission_interface/test_results/transmission_interface/gtest-differential_transmission_loader_test.xml" "--return-code" "/home/akingse/tempopkg_ws/devel_isolated/transmission_interface/lib/transmission_interface/differential_transmission_loader_test --gtest_output=xml:/home/akingse/tempopkg_ws/build_isolated/transmission_interface/test_results/transmission_interface/gtest-differential_transmission_loader_test.xml")
set_tests_properties(_ctest_transmission_interface_gtest_differential_transmission_loader_test PROPERTIES  _BACKTRACE_TRIPLES "/opt/ros/kinetic/share/catkin/cmake/test/tests.cmake;160;add_test;/opt/ros/kinetic/share/catkin/cmake/test/gtest.cmake;98;catkin_run_tests_target;/opt/ros/kinetic/share/catkin/cmake/test/gtest.cmake;37;_catkin_add_google_test;/home/akingse/tempopkg_ws/src/ros_control/transmission_interface/CMakeLists.txt;108;catkin_add_gtest;/home/akingse/tempopkg_ws/src/ros_control/transmission_interface/CMakeLists.txt;0;")
add_test(_ctest_transmission_interface_gtest_four_bar_linkage_transmission_loader_test "/home/akingse/tempopkg_ws/build_isolated/transmission_interface/catkin_generated/env_cached.sh" "/usr/bin/python2" "/opt/ros/kinetic/share/catkin/cmake/test/run_tests.py" "/home/akingse/tempopkg_ws/build_isolated/transmission_interface/test_results/transmission_interface/gtest-four_bar_linkage_transmission_loader_test.xml" "--return-code" "/home/akingse/tempopkg_ws/devel_isolated/transmission_interface/lib/transmission_interface/four_bar_linkage_transmission_loader_test --gtest_output=xml:/home/akingse/tempopkg_ws/build_isolated/transmission_interface/test_results/transmission_interface/gtest-four_bar_linkage_transmission_loader_test.xml")
set_tests_properties(_ctest_transmission_interface_gtest_four_bar_linkage_transmission_loader_test PROPERTIES  _BACKTRACE_TRIPLES "/opt/ros/kinetic/share/catkin/cmake/test/tests.cmake;160;add_test;/opt/ros/kinetic/share/catkin/cmake/test/gtest.cmake;98;catkin_run_tests_target;/opt/ros/kinetic/share/catkin/cmake/test/gtest.cmake;37;_catkin_add_google_test;/home/akingse/tempopkg_ws/src/ros_control/transmission_interface/CMakeLists.txt;111;catkin_add_gtest;/home/akingse/tempopkg_ws/src/ros_control/transmission_interface/CMakeLists.txt;0;")
add_test(_ctest_transmission_interface_gtest_transmission_interface_loader_test "/home/akingse/tempopkg_ws/build_isolated/transmission_interface/catkin_generated/env_cached.sh" "/usr/bin/python2" "/opt/ros/kinetic/share/catkin/cmake/test/run_tests.py" "/home/akingse/tempopkg_ws/build_isolated/transmission_interface/test_results/transmission_interface/gtest-transmission_interface_loader_test.xml" "--return-code" "/home/akingse/tempopkg_ws/devel_isolated/transmission_interface/lib/transmission_interface/transmission_interface_loader_test --gtest_output=xml:/home/akingse/tempopkg_ws/build_isolated/transmission_interface/test_results/transmission_interface/gtest-transmission_interface_loader_test.xml")
set_tests_properties(_ctest_transmission_interface_gtest_transmission_interface_loader_test PROPERTIES  _BACKTRACE_TRIPLES "/opt/ros/kinetic/share/catkin/cmake/test/tests.cmake;160;add_test;/opt/ros/kinetic/share/catkin/cmake/test/gtest.cmake;98;catkin_run_tests_target;/opt/ros/kinetic/share/catkin/cmake/test/gtest.cmake;37;_catkin_add_google_test;/home/akingse/tempopkg_ws/src/ros_control/transmission_interface/CMakeLists.txt;114;catkin_add_gtest;/home/akingse/tempopkg_ws/src/ros_control/transmission_interface/CMakeLists.txt;0;")
subdirs("gtest")
