set(_CATKIN_CURRENT_PACKAGE "rrbot_control")
set(rrbot_control_VERSION "0.0.0")
set(rrbot_control_MAINTAINER "Dave Coleman <davetcoleman@gmail.com>")
set(rrbot_control_PACKAGE_FORMAT "1")
set(rrbot_control_BUILD_DEPENDS )
set(rrbot_control_BUILD_EXPORT_DEPENDS "controller_manager" "joint_state_controller" "robot_state_publisher" "rqt_gui" "effort_controllers")
set(rrbot_control_BUILDTOOL_DEPENDS "catkin")
set(rrbot_control_BUILDTOOL_EXPORT_DEPENDS )
set(rrbot_control_EXEC_DEPENDS "controller_manager" "joint_state_controller" "robot_state_publisher" "rqt_gui" "effort_controllers")
set(rrbot_control_RUN_DEPENDS "controller_manager" "joint_state_controller" "robot_state_publisher" "rqt_gui" "effort_controllers")
set(rrbot_control_TEST_DEPENDS )
set(rrbot_control_DOC_DEPENDS )
set(rrbot_control_URL_WEBSITE "http://http://gazebosim.org/w/index.php?title=Tutorials/1.9/Using_A_URDF_In_Gazebo")
set(rrbot_control_URL_BUGTRACKER "https://github.com/osrf/gazebo_ros_demos/issues")
set(rrbot_control_URL_REPOSITORY "https://github.com/osrf/gazebo_ros_demos")
set(rrbot_control_DEPRECATED "")