set(_CATKIN_CURRENT_PACKAGE "controller_manager")
set(controller_manager_VERSION "0.19.4")
set(controller_manager_MAINTAINER "Bence Magyar <bence.magyar.robotics@gmail.com>, Enrique Fernandez <enrique.fernandez.perdomo@gmail.com>, Mathias Lüdtke <mathias.luedtke@ipa.fraunhofer.de>")
set(controller_manager_PACKAGE_FORMAT "3")
set(controller_manager_BUILD_DEPENDS "controller_interface" "controller_manager_msgs" "hardware_interface" "pluginlib" "roscpp")
set(controller_manager_BUILD_EXPORT_DEPENDS "controller_interface" "controller_manager_msgs" "hardware_interface" "pluginlib" "roscpp")
set(controller_manager_BUILDTOOL_DEPENDS "catkin" "python-setuptools" "python3-setuptools")
set(controller_manager_BUILDTOOL_EXPORT_DEPENDS )
set(controller_manager_EXEC_DEPENDS "std_msgs" "rosparam" "rospy" "roscpp")
set(controller_manager_RUN_DEPENDS "std_msgs" "rosparam" "rospy" "roscpp" "controller_interface" "controller_manager_msgs" "hardware_interface" "pluginlib")
set(controller_manager_TEST_DEPENDS "rostest")
set(controller_manager_DOC_DEPENDS )
set(controller_manager_URL_WEBSITE "https://github.com/ros-controls/ros_control/wiki")
set(controller_manager_URL_BUGTRACKER "https://github.com/ros-controls/ros_control/issues")
set(controller_manager_URL_REPOSITORY "https://github.com/ros-controls/ros_control")
set(controller_manager_DEPRECATED "")