set(controller_manager_SETUP_PY_SETUP_MODULE "setuptools")
set(controller_manager_SETUP_PY_VERSION "0.19.4")
set(controller_manager_SETUP_PY_SCRIPTS "")
set(controller_manager_SETUP_PY_PACKAGES "controller_manager")
set(controller_manager_SETUP_PY_PACKAGE_DIRS "src/controller_manager")
set(controller_manager_SETUP_PY_MODULES "")
set(controller_manager_SETUP_PY_MODULE_DIRS "")