set(_CATKIN_CURRENT_PACKAGE "combined_robot_hw_tests")
set(combined_robot_hw_tests_VERSION "0.19.4")
set(combined_robot_hw_tests_MAINTAINER "Bence Magyar <bence.magyar.robotics@gmail.com>, Toni Oliver <toni@shadowrobot.com>, Enrique Fernandez <enrique.fernandez.perdomo@gmail.com>, Mathias Lüdtke <mathias.luedtke@ipa.fraunhofer.de>")
set(combined_robot_hw_tests_PACKAGE_FORMAT "3")
set(combined_robot_hw_tests_BUILD_DEPENDS "pluginlib" "combined_robot_hw" "controller_manager" "hardware_interface" "roscpp")
set(combined_robot_hw_tests_BUILD_EXPORT_DEPENDS "pluginlib" "combined_robot_hw" "controller_manager" "hardware_interface" "roscpp")
set(combined_robot_hw_tests_BUILDTOOL_DEPENDS "catkin")
set(combined_robot_hw_tests_BUILDTOOL_EXPORT_DEPENDS )
set(combined_robot_hw_tests_EXEC_DEPENDS "combined_robot_hw" "controller_manager" "hardware_interface" "roscpp")
set(combined_robot_hw_tests_RUN_DEPENDS "combined_robot_hw" "controller_manager" "hardware_interface" "roscpp" "pluginlib")
set(combined_robot_hw_tests_TEST_DEPENDS "controller_manager_msgs" "controller_manager_tests" "rostest")
set(combined_robot_hw_tests_DOC_DEPENDS )
set(combined_robot_hw_tests_URL_WEBSITE "https://github.com/ros-controls/ros_control/wiki")
set(combined_robot_hw_tests_URL_BUGTRACKER "https://github.com/ros-controls/ros_control/issues")
set(combined_robot_hw_tests_URL_REPOSITORY "https://github.com/ros-controls/ros_control")
set(combined_robot_hw_tests_DEPRECATED "")