set(_CATKIN_CURRENT_PACKAGE "ros_control")
set(ros_control_VERSION "0.19.4")
set(ros_control_MAINTAINER "Bence Magyar <bence.magyar.robotics@gmail.com>, Enrique Fernandez <enrique.fernandez.perdomo@gmail.com>, Mathias Lüdtke <mathias.luedtke@ipa.fraunhofer.de>")
set(ros_control_PACKAGE_FORMAT "3")
set(ros_control_BUILD_DEPENDS )
set(ros_control_BUILD_EXPORT_DEPENDS )
set(ros_control_BUILDTOOL_DEPENDS "catkin")
set(ros_control_BUILDTOOL_EXPORT_DEPENDS )
set(ros_control_EXEC_DEPENDS "combined_robot_hw" "controller_interface" "controller_manager" "controller_manager_msgs" "hardware_interface" "joint_limits_interface" "realtime_tools" "transmission_interface")
set(ros_control_RUN_DEPENDS "combined_robot_hw" "controller_interface" "controller_manager" "controller_manager_msgs" "hardware_interface" "joint_limits_interface" "realtime_tools" "transmission_interface")
set(ros_control_TEST_DEPENDS )
set(ros_control_DOC_DEPENDS )
set(ros_control_URL_WEBSITE "http://ros.org/wiki/ros_control")
set(ros_control_URL_BUGTRACKER "https://github.com/ros-controls/ros_control/issues")
set(ros_control_URL_REPOSITORY "https://github.com/ros-controls/ros_control/")
set(ros_control_DEPRECATED "")