# CMake generated Testfile for 
# Source directory: /home/akingse/tempopkg_ws/src/velodyne/velodyne_driver
# Build directory: /home/akingse/tempopkg_ws/build_isolated/velodyne_driver
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(_ctest_velodyne_driver_rostest_tests_pcap_node_hertz.test "/home/akingse/tempopkg_ws/build_isolated/velodyne_driver/catkin_generated/env_cached.sh" "/usr/bin/python2" "/opt/ros/kinetic/share/catkin/cmake/test/run_tests.py" "/home/akingse/tempopkg_ws/build_isolated/velodyne_driver/test_results/velodyne_driver/rostest-tests_pcap_node_hertz.xml" "--return-code" "/opt/ros/kinetic/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/akingse/tempopkg_ws/src/velodyne/velodyne_driver --package=velodyne_driver --results-filename tests_pcap_node_hertz.xml --results-base-dir \"/home/akingse/tempopkg_ws/build_isolated/velodyne_driver/test_results\" /home/akingse/tempopkg_ws/src/velodyne/velodyne_driver/tests/pcap_node_hertz.test ")
set_tests_properties(_ctest_velodyne_driver_rostest_tests_pcap_node_hertz.test PROPERTIES  _BACKTRACE_TRIPLES "/opt/ros/kinetic/share/catkin/cmake/test/tests.cmake;160;add_test;/opt/ros/kinetic/share/rostest/cmake/rostest-extras.cmake;52;catkin_run_tests_target;/home/akingse/tempopkg_ws/src/velodyne/velodyne_driver/CMakeLists.txt;79;add_rostest;/home/akingse/tempopkg_ws/src/velodyne/velodyne_driver/CMakeLists.txt;0;")
add_test(_ctest_velodyne_driver_rostest_tests_pcap_nodelet_hertz.test "/home/akingse/tempopkg_ws/build_isolated/velodyne_driver/catkin_generated/env_cached.sh" "/usr/bin/python2" "/opt/ros/kinetic/share/catkin/cmake/test/run_tests.py" "/home/akingse/tempopkg_ws/build_isolated/velodyne_driver/test_results/velodyne_driver/rostest-tests_pcap_nodelet_hertz.xml" "--return-code" "/opt/ros/kinetic/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/akingse/tempopkg_ws/src/velodyne/velodyne_driver --package=velodyne_driver --results-filename tests_pcap_nodelet_hertz.xml --results-base-dir \"/home/akingse/tempopkg_ws/build_isolated/velodyne_driver/test_results\" /home/akingse/tempopkg_ws/src/velodyne/velodyne_driver/tests/pcap_nodelet_hertz.test ")
set_tests_properties(_ctest_velodyne_driver_rostest_tests_pcap_nodelet_hertz.test PROPERTIES  _BACKTRACE_TRIPLES "/opt/ros/kinetic/share/catkin/cmake/test/tests.cmake;160;add_test;/opt/ros/kinetic/share/rostest/cmake/rostest-extras.cmake;52;catkin_run_tests_target;/home/akingse/tempopkg_ws/src/velodyne/velodyne_driver/CMakeLists.txt;80;add_rostest;/home/akingse/tempopkg_ws/src/velodyne/velodyne_driver/CMakeLists.txt;0;")
add_test(_ctest_velodyne_driver_rostest_tests_pcap_32e_node_hertz.test "/home/akingse/tempopkg_ws/build_isolated/velodyne_driver/catkin_generated/env_cached.sh" "/usr/bin/python2" "/opt/ros/kinetic/share/catkin/cmake/test/run_tests.py" "/home/akingse/tempopkg_ws/build_isolated/velodyne_driver/test_results/velodyne_driver/rostest-tests_pcap_32e_node_hertz.xml" "--return-code" "/opt/ros/kinetic/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/akingse/tempopkg_ws/src/velodyne/velodyne_driver --package=velodyne_driver --results-filename tests_pcap_32e_node_hertz.xml --results-base-dir \"/home/akingse/tempopkg_ws/build_isolated/velodyne_driver/test_results\" /home/akingse/tempopkg_ws/src/velodyne/velodyne_driver/tests/pcap_32e_node_hertz.test ")
set_tests_properties(_ctest_velodyne_driver_rostest_tests_pcap_32e_node_hertz.test PROPERTIES  _BACKTRACE_TRIPLES "/opt/ros/kinetic/share/catkin/cmake/test/tests.cmake;160;add_test;/opt/ros/kinetic/share/rostest/cmake/rostest-extras.cmake;52;catkin_run_tests_target;/home/akingse/tempopkg_ws/src/velodyne/velodyne_driver/CMakeLists.txt;81;add_rostest;/home/akingse/tempopkg_ws/src/velodyne/velodyne_driver/CMakeLists.txt;0;")
add_test(_ctest_velodyne_driver_rostest_tests_pcap_32e_nodelet_hertz.test "/home/akingse/tempopkg_ws/build_isolated/velodyne_driver/catkin_generated/env_cached.sh" "/usr/bin/python2" "/opt/ros/kinetic/share/catkin/cmake/test/run_tests.py" "/home/akingse/tempopkg_ws/build_isolated/velodyne_driver/test_results/velodyne_driver/rostest-tests_pcap_32e_nodelet_hertz.xml" "--return-code" "/opt/ros/kinetic/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/akingse/tempopkg_ws/src/velodyne/velodyne_driver --package=velodyne_driver --results-filename tests_pcap_32e_nodelet_hertz.xml --results-base-dir \"/home/akingse/tempopkg_ws/build_isolated/velodyne_driver/test_results\" /home/akingse/tempopkg_ws/src/velodyne/velodyne_driver/tests/pcap_32e_nodelet_hertz.test ")
set_tests_properties(_ctest_velodyne_driver_rostest_tests_pcap_32e_nodelet_hertz.test PROPERTIES  _BACKTRACE_TRIPLES "/opt/ros/kinetic/share/catkin/cmake/test/tests.cmake;160;add_test;/opt/ros/kinetic/share/rostest/cmake/rostest-extras.cmake;52;catkin_run_tests_target;/home/akingse/tempopkg_ws/src/velodyne/velodyne_driver/CMakeLists.txt;82;add_rostest;/home/akingse/tempopkg_ws/src/velodyne/velodyne_driver/CMakeLists.txt;0;")
add_test(_ctest_velodyne_driver_rostest_tests_pcap_vlp16_node_hertz.test "/home/akingse/tempopkg_ws/build_isolated/velodyne_driver/catkin_generated/env_cached.sh" "/usr/bin/python2" "/opt/ros/kinetic/share/catkin/cmake/test/run_tests.py" "/home/akingse/tempopkg_ws/build_isolated/velodyne_driver/test_results/velodyne_driver/rostest-tests_pcap_vlp16_node_hertz.xml" "--return-code" "/opt/ros/kinetic/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/akingse/tempopkg_ws/src/velodyne/velodyne_driver --package=velodyne_driver --results-filename tests_pcap_vlp16_node_hertz.xml --results-base-dir \"/home/akingse/tempopkg_ws/build_isolated/velodyne_driver/test_results\" /home/akingse/tempopkg_ws/src/velodyne/velodyne_driver/tests/pcap_vlp16_node_hertz.test ")
set_tests_properties(_ctest_velodyne_driver_rostest_tests_pcap_vlp16_node_hertz.test PROPERTIES  _BACKTRACE_TRIPLES "/opt/ros/kinetic/share/catkin/cmake/test/tests.cmake;160;add_test;/opt/ros/kinetic/share/rostest/cmake/rostest-extras.cmake;52;catkin_run_tests_target;/home/akingse/tempopkg_ws/src/velodyne/velodyne_driver/CMakeLists.txt;83;add_rostest;/home/akingse/tempopkg_ws/src/velodyne/velodyne_driver/CMakeLists.txt;0;")
add_test(_ctest_velodyne_driver_rostest_tests_pcap_vlp16_nodelet_hertz.test "/home/akingse/tempopkg_ws/build_isolated/velodyne_driver/catkin_generated/env_cached.sh" "/usr/bin/python2" "/opt/ros/kinetic/share/catkin/cmake/test/run_tests.py" "/home/akingse/tempopkg_ws/build_isolated/velodyne_driver/test_results/velodyne_driver/rostest-tests_pcap_vlp16_nodelet_hertz.xml" "--return-code" "/opt/ros/kinetic/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/akingse/tempopkg_ws/src/velodyne/velodyne_driver --package=velodyne_driver --results-filename tests_pcap_vlp16_nodelet_hertz.xml --results-base-dir \"/home/akingse/tempopkg_ws/build_isolated/velodyne_driver/test_results\" /home/akingse/tempopkg_ws/src/velodyne/velodyne_driver/tests/pcap_vlp16_nodelet_hertz.test ")
set_tests_properties(_ctest_velodyne_driver_rostest_tests_pcap_vlp16_nodelet_hertz.test PROPERTIES  _BACKTRACE_TRIPLES "/opt/ros/kinetic/share/catkin/cmake/test/tests.cmake;160;add_test;/opt/ros/kinetic/share/rostest/cmake/rostest-extras.cmake;52;catkin_run_tests_target;/home/akingse/tempopkg_ws/src/velodyne/velodyne_driver/CMakeLists.txt;84;add_rostest;/home/akingse/tempopkg_ws/src/velodyne/velodyne_driver/CMakeLists.txt;0;")
add_test(_ctest_velodyne_driver_roslaunch-check_launch "/home/akingse/tempopkg_ws/build_isolated/velodyne_driver/catkin_generated/env_cached.sh" "/usr/bin/python2" "/opt/ros/kinetic/share/catkin/cmake/test/run_tests.py" "/home/akingse/tempopkg_ws/build_isolated/velodyne_driver/test_results/velodyne_driver/roslaunch-check_launch.xml" "--return-code" "/usr/local/bin/cmake -E make_directory /home/akingse/tempopkg_ws/build_isolated/velodyne_driver/test_results/velodyne_driver" "/opt/ros/kinetic/share/roslaunch/cmake/../scripts/roslaunch-check -o '/home/akingse/tempopkg_ws/build_isolated/velodyne_driver/test_results/velodyne_driver/roslaunch-check_launch.xml' '/home/akingse/tempopkg_ws/src/velodyne/velodyne_driver/launch' ")
set_tests_properties(_ctest_velodyne_driver_roslaunch-check_launch PROPERTIES  _BACKTRACE_TRIPLES "/opt/ros/kinetic/share/catkin/cmake/test/tests.cmake;160;add_test;/opt/ros/kinetic/share/roslaunch/cmake/roslaunch-extras.cmake;58;catkin_run_tests_target;/home/akingse/tempopkg_ws/src/velodyne/velodyne_driver/CMakeLists.txt;87;roslaunch_add_file_check;/home/akingse/tempopkg_ws/src/velodyne/velodyne_driver/CMakeLists.txt;0;")
add_test(_ctest_velodyne_driver_gtest_time_test "/home/akingse/tempopkg_ws/build_isolated/velodyne_driver/catkin_generated/env_cached.sh" "/usr/bin/python2" "/opt/ros/kinetic/share/catkin/cmake/test/run_tests.py" "/home/akingse/tempopkg_ws/build_isolated/velodyne_driver/test_results/velodyne_driver/gtest-time_test.xml" "--return-code" "/home/akingse/tempopkg_ws/devel_isolated/velodyne_driver/lib/velodyne_driver/time_test --gtest_output=xml:/home/akingse/tempopkg_ws/build_isolated/velodyne_driver/test_results/velodyne_driver/gtest-time_test.xml")
set_tests_properties(_ctest_velodyne_driver_gtest_time_test PROPERTIES  _BACKTRACE_TRIPLES "/opt/ros/kinetic/share/catkin/cmake/test/tests.cmake;160;add_test;/opt/ros/kinetic/share/catkin/cmake/test/gtest.cmake;98;catkin_run_tests_target;/opt/ros/kinetic/share/catkin/cmake/test/gtest.cmake;37;_catkin_add_google_test;/home/akingse/tempopkg_ws/src/velodyne/velodyne_driver/CMakeLists.txt;90;catkin_add_gtest;/home/akingse/tempopkg_ws/src/velodyne/velodyne_driver/CMakeLists.txt;0;")
subdirs("gtest")
subdirs("src/lib")
subdirs("src/driver")
