# CMake generated Testfile for 
# Source directory: /home/akingse/tempopkg_ws/src/ros_control/controller_manager_tests
# Build directory: /home/akingse/tempopkg_ws/build_isolated/controller_manager_tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(_ctest_controller_manager_tests_nosetests_test "/home/akingse/tempopkg_ws/build_isolated/controller_manager_tests/catkin_generated/env_cached.sh" "/usr/bin/python2" "/opt/ros/kinetic/share/catkin/cmake/test/run_tests.py" "/home/akingse/tempopkg_ws/build_isolated/controller_manager_tests/test_results/controller_manager_tests/nosetests-test.xml" "--return-code" "\"/usr/local/bin/cmake\" -E make_directory /home/akingse/tempopkg_ws/build_isolated/controller_manager_tests/test_results/controller_manager_tests" "/usr/bin/nosetests-2.7 -P --process-timeout=60 --where=/home/akingse/tempopkg_ws/src/ros_control/controller_manager_tests/test --with-xunit --xunit-file=/home/akingse/tempopkg_ws/build_isolated/controller_manager_tests/test_results/controller_manager_tests/nosetests-test.xml")
set_tests_properties(_ctest_controller_manager_tests_nosetests_test PROPERTIES  _BACKTRACE_TRIPLES "/opt/ros/kinetic/share/catkin/cmake/test/tests.cmake;160;add_test;/opt/ros/kinetic/share/catkin/cmake/test/nosetests.cmake;83;catkin_run_tests_target;/home/akingse/tempopkg_ws/src/ros_control/controller_manager_tests/CMakeLists.txt;48;catkin_add_nosetests;/home/akingse/tempopkg_ws/src/ros_control/controller_manager_tests/CMakeLists.txt;0;")
add_test(_ctest_controller_manager_tests_rostest_test_cm_test.test "/home/akingse/tempopkg_ws/build_isolated/controller_manager_tests/catkin_generated/env_cached.sh" "/usr/bin/python2" "/opt/ros/kinetic/share/catkin/cmake/test/run_tests.py" "/home/akingse/tempopkg_ws/build_isolated/controller_manager_tests/test_results/controller_manager_tests/rostest-test_cm_test.xml" "--return-code" "/opt/ros/kinetic/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/akingse/tempopkg_ws/src/ros_control/controller_manager_tests --package=controller_manager_tests --results-filename test_cm_test.xml --results-base-dir \"/home/akingse/tempopkg_ws/build_isolated/controller_manager_tests/test_results\" /home/akingse/tempopkg_ws/src/ros_control/controller_manager_tests/test/cm_test.test ")
set_tests_properties(_ctest_controller_manager_tests_rostest_test_cm_test.test PROPERTIES  _BACKTRACE_TRIPLES "/opt/ros/kinetic/share/catkin/cmake/test/tests.cmake;160;add_test;/opt/ros/kinetic/share/rostest/cmake/rostest-extras.cmake;52;catkin_run_tests_target;/home/akingse/tempopkg_ws/src/ros_control/controller_manager_tests/CMakeLists.txt;50;add_rostest;/home/akingse/tempopkg_ws/src/ros_control/controller_manager_tests/CMakeLists.txt;0;")
add_test(_ctest_controller_manager_tests_rostest_test_cm_msgs_utils_rostest.test "/home/akingse/tempopkg_ws/build_isolated/controller_manager_tests/catkin_generated/env_cached.sh" "/usr/bin/python2" "/opt/ros/kinetic/share/catkin/cmake/test/run_tests.py" "/home/akingse/tempopkg_ws/build_isolated/controller_manager_tests/test_results/controller_manager_tests/rostest-test_cm_msgs_utils_rostest.xml" "--return-code" "/opt/ros/kinetic/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/akingse/tempopkg_ws/src/ros_control/controller_manager_tests --package=controller_manager_tests --results-filename test_cm_msgs_utils_rostest.xml --results-base-dir \"/home/akingse/tempopkg_ws/build_isolated/controller_manager_tests/test_results\" /home/akingse/tempopkg_ws/src/ros_control/controller_manager_tests/test/cm_msgs_utils_rostest.test ")
set_tests_properties(_ctest_controller_manager_tests_rostest_test_cm_msgs_utils_rostest.test PROPERTIES  _BACKTRACE_TRIPLES "/opt/ros/kinetic/share/catkin/cmake/test/tests.cmake;160;add_test;/opt/ros/kinetic/share/rostest/cmake/rostest-extras.cmake;52;catkin_run_tests_target;/home/akingse/tempopkg_ws/src/ros_control/controller_manager_tests/CMakeLists.txt;52;add_rostest;/home/akingse/tempopkg_ws/src/ros_control/controller_manager_tests/CMakeLists.txt;0;")
add_test(_ctest_controller_manager_tests_rostest_test_controller_manager_scripts.test "/home/akingse/tempopkg_ws/build_isolated/controller_manager_tests/catkin_generated/env_cached.sh" "/usr/bin/python2" "/opt/ros/kinetic/share/catkin/cmake/test/run_tests.py" "/home/akingse/tempopkg_ws/build_isolated/controller_manager_tests/test_results/controller_manager_tests/rostest-test_controller_manager_scripts.xml" "--return-code" "/opt/ros/kinetic/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/akingse/tempopkg_ws/src/ros_control/controller_manager_tests --package=controller_manager_tests --results-filename test_controller_manager_scripts.xml --results-base-dir \"/home/akingse/tempopkg_ws/build_isolated/controller_manager_tests/test_results\" /home/akingse/tempopkg_ws/src/ros_control/controller_manager_tests/test/controller_manager_scripts.test ")
set_tests_properties(_ctest_controller_manager_tests_rostest_test_controller_manager_scripts.test PROPERTIES  _BACKTRACE_TRIPLES "/opt/ros/kinetic/share/catkin/cmake/test/tests.cmake;160;add_test;/opt/ros/kinetic/share/rostest/cmake/rostest-extras.cmake;52;catkin_run_tests_target;/home/akingse/tempopkg_ws/src/ros_control/controller_manager_tests/CMakeLists.txt;54;add_rostest;/home/akingse/tempopkg_ws/src/ros_control/controller_manager_tests/CMakeLists.txt;0;")
add_test(_ctest_controller_manager_tests_rostest_test_controller_manager_interface_test.test "/home/akingse/tempopkg_ws/build_isolated/controller_manager_tests/catkin_generated/env_cached.sh" "/usr/bin/python2" "/opt/ros/kinetic/share/catkin/cmake/test/run_tests.py" "/home/akingse/tempopkg_ws/build_isolated/controller_manager_tests/test_results/controller_manager_tests/rostest-test_controller_manager_interface_test.xml" "--return-code" "/opt/ros/kinetic/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/akingse/tempopkg_ws/src/ros_control/controller_manager_tests --package=controller_manager_tests --results-filename test_controller_manager_interface_test.xml --results-base-dir \"/home/akingse/tempopkg_ws/build_isolated/controller_manager_tests/test_results\" /home/akingse/tempopkg_ws/src/ros_control/controller_manager_tests/test/controller_manager_interface_test.test ")
set_tests_properties(_ctest_controller_manager_tests_rostest_test_controller_manager_interface_test.test PROPERTIES  _BACKTRACE_TRIPLES "/opt/ros/kinetic/share/catkin/cmake/test/tests.cmake;160;add_test;/opt/ros/kinetic/share/rostest/cmake/rostest-extras.cmake;52;catkin_run_tests_target;/home/akingse/tempopkg_ws/src/ros_control/controller_manager_tests/CMakeLists.txt;56;add_rostest;/home/akingse/tempopkg_ws/src/ros_control/controller_manager_tests/CMakeLists.txt;0;")
subdirs("gtest")
