set(_CATKIN_CURRENT_PACKAGE "transmission_interface")
set(transmission_interface_VERSION "0.19.4")
set(transmission_interface_MAINTAINER "Bence Magyar <bence.magyar.robotics@gmail.com>, Enrique Fernandez <enrique.fernandez.perdomo@gmail.com>, Mathias Lüdtke <mathias.luedtke@ipa.fraunhofer.de>")
set(transmission_interface_PACKAGE_FORMAT "3")
set(transmission_interface_BUILD_DEPENDS "cmake_modules" "hardware_interface" "pluginlib" "roscpp" "tinyxml")
set(transmission_interface_BUILD_EXPORT_DEPENDS "hardware_interface" "pluginlib" "roscpp" "tinyxml")
set(transmission_interface_BUILDTOOL_DEPENDS "catkin")
set(transmission_interface_BUILDTOOL_EXPORT_DEPENDS )
set(transmission_interface_EXEC_DEPENDS "roscpp" "tinyxml")
set(transmission_interface_RUN_DEPENDS "roscpp" "tinyxml" "hardware_interface" "pluginlib")
set(transmission_interface_TEST_DEPENDS "resource_retriever")
set(transmission_interface_DOC_DEPENDS )
set(transmission_interface_URL_WEBSITE "https://github.com/ros-controls/ros_control/wiki")
set(transmission_interface_URL_BUGTRACKER "https://github.com/ros-controls/ros_control/issues")
set(transmission_interface_URL_REPOSITORY "https://github.com/ros-controls/ros_control")
set(transmission_interface_DEPRECATED "")