set(_CATKIN_CURRENT_PACKAGE "rrbot_gazebo")
set(rrbot_gazebo_VERSION "0.1.0")
set(rrbot_gazebo_MAINTAINER "Dave Coleman <davetcoleman@gmail.com>")
set(rrbot_gazebo_PACKAGE_FORMAT "1")
set(rrbot_gazebo_BUILD_DEPENDS )
set(rrbot_gazebo_BUILD_EXPORT_DEPENDS "gazebo_plugins" "gazebo_ros" "gazebo_ros_control" "rrbot_control" "rrbot_description" "xacro")
set(rrbot_gazebo_BUILDTOOL_DEPENDS "catkin")
set(rrbot_gazebo_BUILDTOOL_EXPORT_DEPENDS )
set(rrbot_gazebo_EXEC_DEPENDS "gazebo_plugins" "gazebo_ros" "gazebo_ros_control" "rrbot_control" "rrbot_description" "xacro")
set(rrbot_gazebo_RUN_DEPENDS "gazebo_plugins" "gazebo_ros" "gazebo_ros_control" "rrbot_control" "rrbot_description" "xacro")
set(rrbot_gazebo_TEST_DEPENDS )
set(rrbot_gazebo_DOC_DEPENDS )
set(rrbot_gazebo_URL_WEBSITE "http://gazebosim.org/w/index.php?title=Tutorials/1.9/Using_A_URDF_In_Gazebo")
set(rrbot_gazebo_URL_BUGTRACKER "https://github.com/osrf/gazebo_ros_demos/issues")
set(rrbot_gazebo_URL_REPOSITORY "https://github.com/osrf/gazebo_ros_demos")
set(rrbot_gazebo_DEPRECATED "")