set(_CATKIN_CURRENT_PACKAGE "imu_sensor_controller")
set(imu_sensor_controller_VERSION "0.18.1")
set(imu_sensor_controller_MAINTAINER "Bence Magyar <bence.magyar.robotics@gmail.com>, Mathias Lüdtke <mathias.luedtke@ipa.fraunhofer.de>, Enrique Fernandez <enrique.fernandez.perdomo@gmail.com>")
set(imu_sensor_controller_PACKAGE_FORMAT "3")
set(imu_sensor_controller_BUILD_DEPENDS "hardware_interface" "pluginlib" "sensor_msgs" "controller_interface" "realtime_tools" "roscpp")
set(imu_sensor_controller_BUILD_EXPORT_DEPENDS "hardware_interface" "sensor_msgs" "controller_interface" "realtime_tools" "roscpp")
set(imu_sensor_controller_BUILDTOOL_DEPENDS "catkin")
set(imu_sensor_controller_BUILDTOOL_EXPORT_DEPENDS )
set(imu_sensor_controller_EXEC_DEPENDS "controller_manager" "controller_interface" "realtime_tools" "roscpp")
set(imu_sensor_controller_RUN_DEPENDS "controller_manager" "controller_interface" "realtime_tools" "roscpp" "hardware_interface" "sensor_msgs")
set(imu_sensor_controller_TEST_DEPENDS )
set(imu_sensor_controller_DOC_DEPENDS )
set(imu_sensor_controller_URL_WEBSITE "https://github.com/ros-controls/ros_controllers/wiki")
set(imu_sensor_controller_URL_BUGTRACKER "https://github.com/ros-controls/ros_controllers/issues")
set(imu_sensor_controller_URL_REPOSITORY "https://github.com/ros-controls/ros_controllers")
set(imu_sensor_controller_DEPRECATED "")