set(_CATKIN_CURRENT_PACKAGE "position_controllers")
set(position_controllers_VERSION "0.18.1")
set(position_controllers_MAINTAINER "Bence Magyar <bence.magyar.robotics@gmail.com>, Mathias Lüdtke <mathias.luedtke@ipa.fraunhofer.de>, Enrique Fernandez <enrique.fernandez.perdomo@gmail.com>")
set(position_controllers_PACKAGE_FORMAT "3")
set(position_controllers_BUILD_DEPENDS "forward_command_controller" "hardware_interface" "pluginlib" "roscpp")
set(position_controllers_BUILD_EXPORT_DEPENDS "forward_command_controller" "hardware_interface")
set(position_controllers_BUILDTOOL_DEPENDS "catkin")
set(position_controllers_BUILDTOOL_EXPORT_DEPENDS )
set(position_controllers_EXEC_DEPENDS "controller_interface" "roscpp")
set(position_controllers_RUN_DEPENDS "controller_interface" "roscpp" "forward_command_controller" "hardware_interface")
set(position_controllers_TEST_DEPENDS )
set(position_controllers_DOC_DEPENDS )
set(position_controllers_URL_WEBSITE "https://github.com/ros-controls/ros_controllers/wiki")
set(position_controllers_URL_BUGTRACKER "https://github.com/ros-controls/ros_controllers/issues")
set(position_controllers_URL_REPOSITORY "https://github.com/ros-controls/ros_controllers")
set(position_controllers_DEPRECATED "")