set(_CATKIN_CURRENT_PACKAGE "gazebo_tutorials")
set(gazebo_tutorials_VERSION "0.0.0")
set(gazebo_tutorials_MAINTAINER "dave <dave@todo.todo>")
set(gazebo_tutorials_PACKAGE_FORMAT "1")
set(gazebo_tutorials_BUILD_DEPENDS "gazebo_ros" "gazebo" "roscpp")
set(gazebo_tutorials_BUILD_EXPORT_DEPENDS "gazebo_ros" "roscpp")
set(gazebo_tutorials_BUILDTOOL_DEPENDS "catkin")
set(gazebo_tutorials_BUILDTOOL_EXPORT_DEPENDS )
set(gazebo_tutorials_EXEC_DEPENDS "gazebo_ros" "roscpp")
set(gazebo_tutorials_RUN_DEPENDS "gazebo_ros" "roscpp")
set(gazebo_tutorials_TEST_DEPENDS )
set(gazebo_tutorials_DOC_DEPENDS )
set(gazebo_tutorials_URL_WEBSITE "")
set(gazebo_tutorials_URL_BUGTRACKER "")
set(gazebo_tutorials_URL_REPOSITORY "")
set(gazebo_tutorials_DEPRECATED "")