# CMake generated Testfile for 
# Source directory: /home/akingse/tempopkg_ws/src/ros_control/combined_robot_hw_tests
# Build directory: /home/akingse/tempopkg_ws/build_isolated/combined_robot_hw_tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(_ctest_combined_robot_hw_tests_rostest_test_combined_robot_hw_test.test "/home/akingse/tempopkg_ws/build_isolated/combined_robot_hw_tests/catkin_generated/env_cached.sh" "/usr/bin/python2" "/opt/ros/kinetic/share/catkin/cmake/test/run_tests.py" "/home/akingse/tempopkg_ws/build_isolated/combined_robot_hw_tests/test_results/combined_robot_hw_tests/rostest-test_combined_robot_hw_test.xml" "--return-code" "/opt/ros/kinetic/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/akingse/tempopkg_ws/src/ros_control/combined_robot_hw_tests --package=combined_robot_hw_tests --results-filename test_combined_robot_hw_test.xml --results-base-dir \"/home/akingse/tempopkg_ws/build_isolated/combined_robot_hw_tests/test_results\" /home/akingse/tempopkg_ws/src/ros_control/combined_robot_hw_tests/test/combined_robot_hw_test.test ")
set_tests_properties(_ctest_combined_robot_hw_tests_rostest_test_combined_robot_hw_test.test PROPERTIES  _BACKTRACE_TRIPLES "/opt/ros/kinetic/share/catkin/cmake/test/tests.cmake;160;add_test;/opt/ros/kinetic/share/rostest/cmake/rostest-extras.cmake;52;catkin_run_tests_target;/opt/ros/kinetic/share/rostest/cmake/rostest-extras.cmake;80;add_rostest;/opt/ros/kinetic/share/rostest/cmake/rostest-extras.cmake;100;_add_rostest_google_test;/home/akingse/tempopkg_ws/src/ros_control/combined_robot_hw_tests/CMakeLists.txt;40;add_rostest_gtest;/home/akingse/tempopkg_ws/src/ros_control/combined_robot_hw_tests/CMakeLists.txt;0;")
add_test(_ctest_combined_robot_hw_tests_rostest_test_cm_test.test "/home/akingse/tempopkg_ws/build_isolated/combined_robot_hw_tests/catkin_generated/env_cached.sh" "/usr/bin/python2" "/opt/ros/kinetic/share/catkin/cmake/test/run_tests.py" "/home/akingse/tempopkg_ws/build_isolated/combined_robot_hw_tests/test_results/combined_robot_hw_tests/rostest-test_cm_test.xml" "--return-code" "/opt/ros/kinetic/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/akingse/tempopkg_ws/src/ros_control/combined_robot_hw_tests --package=combined_robot_hw_tests --results-filename test_cm_test.xml --results-base-dir \"/home/akingse/tempopkg_ws/build_isolated/combined_robot_hw_tests/test_results\" /home/akingse/tempopkg_ws/src/ros_control/combined_robot_hw_tests/test/cm_test.test ")
set_tests_properties(_ctest_combined_robot_hw_tests_rostest_test_cm_test.test PROPERTIES  _BACKTRACE_TRIPLES "/opt/ros/kinetic/share/catkin/cmake/test/tests.cmake;160;add_test;/opt/ros/kinetic/share/rostest/cmake/rostest-extras.cmake;52;catkin_run_tests_target;/opt/ros/kinetic/share/rostest/cmake/rostest-extras.cmake;80;add_rostest;/opt/ros/kinetic/share/rostest/cmake/rostest-extras.cmake;100;_add_rostest_google_test;/home/akingse/tempopkg_ws/src/ros_control/combined_robot_hw_tests/CMakeLists.txt;46;add_rostest_gtest;/home/akingse/tempopkg_ws/src/ros_control/combined_robot_hw_tests/CMakeLists.txt;0;")
subdirs("gtest")
