set(_CATKIN_CURRENT_PACKAGE "controller_manager_tests")
set(controller_manager_tests_VERSION "0.19.4")
set(controller_manager_tests_MAINTAINER "Bence Magyar <bence.magyar.robotics@gmail.com>, Enrique Fernandez <enrique.fernandez.perdomo@gmail.com>, Mathias Lüdtke <mathias.luedtke@ipa.fraunhofer.de>")
set(controller_manager_tests_PACKAGE_FORMAT "3")
set(controller_manager_tests_BUILD_DEPENDS "hardware_interface" "pluginlib" "controller_interface" "controller_manager" "roscpp")
set(controller_manager_tests_BUILD_EXPORT_DEPENDS "hardware_interface" "pluginlib" "controller_interface" "controller_manager" "roscpp")
set(controller_manager_tests_BUILDTOOL_DEPENDS "catkin" "python-setuptools" "python3-setuptools")
set(controller_manager_tests_BUILDTOOL_EXPORT_DEPENDS )
set(controller_manager_tests_EXEC_DEPENDS "controller_manager_msgs" "rospy" "controller_interface" "controller_manager" "roscpp")
set(controller_manager_tests_RUN_DEPENDS "controller_manager_msgs" "rospy" "controller_interface" "controller_manager" "roscpp" "hardware_interface" "pluginlib")
set(controller_manager_tests_TEST_DEPENDS "rosbash" "rosnode" "rostest")
set(controller_manager_tests_DOC_DEPENDS )
set(controller_manager_tests_URL_WEBSITE "http://ros.org/wiki/controller_manager_tests")
set(controller_manager_tests_URL_BUGTRACKER "https://github.com/ros-controls/ros_control/issues")
set(controller_manager_tests_URL_REPOSITORY "https://github.com/ros-controls/ros_control")
set(controller_manager_tests_DEPRECATED "")