set(_CATKIN_CURRENT_PACKAGE "forward_command_controller")
set(forward_command_controller_VERSION "0.18.1")
set(forward_command_controller_MAINTAINER "Bence Magyar <bence.magyar.robotics@gmail.com>, Mathias Lüdtke <mathias.luedtke@ipa.fraunhofer.de>, Enrique Fernandez <enrique.fernandez.perdomo@gmail.com>")
set(forward_command_controller_PACKAGE_FORMAT "3")
set(forward_command_controller_BUILD_DEPENDS "controller_interface" "hardware_interface" "realtime_tools" "roscpp" "std_msgs")
set(forward_command_controller_BUILD_EXPORT_DEPENDS "controller_interface" "hardware_interface" "realtime_tools" "roscpp" "std_msgs")
set(forward_command_controller_BUILDTOOL_DEPENDS "catkin")
set(forward_command_controller_BUILDTOOL_EXPORT_DEPENDS )
set(forward_command_controller_EXEC_DEPENDS )
set(forward_command_controller_RUN_DEPENDS "controller_interface" "hardware_interface" "realtime_tools" "roscpp" "std_msgs")
set(forward_command_controller_TEST_DEPENDS )
set(forward_command_controller_DOC_DEPENDS )
set(forward_command_controller_URL_WEBSITE "https://github.com/ros-controls/ros_controllers/wiki")
set(forward_command_controller_URL_BUGTRACKER "https://github.com/ros-controls/ros_controllers/issues")
set(forward_command_controller_URL_REPOSITORY "https://github.com/ros-controls/ros_controllers")
set(forward_command_controller_DEPRECATED "")