# CMake generated Testfile for 
# Source directory: /home/akingse/tempopkg_ws/src/ros_control/hardware_interface
# Build directory: /home/akingse/tempopkg_ws/build_isolated/hardware_interface
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(_ctest_hardware_interface_gtest_hardware_resource_manager_test "/home/akingse/tempopkg_ws/build_isolated/hardware_interface/catkin_generated/env_cached.sh" "/usr/bin/python2" "/opt/ros/kinetic/share/catkin/cmake/test/run_tests.py" "/home/akingse/tempopkg_ws/build_isolated/hardware_interface/test_results/hardware_interface/gtest-hardware_resource_manager_test.xml" "--return-code" "/home/akingse/tempopkg_ws/devel_isolated/hardware_interface/lib/hardware_interface/hardware_resource_manager_test --gtest_output=xml:/home/akingse/tempopkg_ws/build_isolated/hardware_interface/test_results/hardware_interface/gtest-hardware_resource_manager_test.xml")
set_tests_properties(_ctest_hardware_interface_gtest_hardware_resource_manager_test PROPERTIES  _BACKTRACE_TRIPLES "/opt/ros/kinetic/share/catkin/cmake/test/tests.cmake;160;add_test;/opt/ros/kinetic/share/catkin/cmake/test/gtest.cmake;98;catkin_run_tests_target;/opt/ros/kinetic/share/catkin/cmake/test/gtest.cmake;37;_catkin_add_google_test;/home/akingse/tempopkg_ws/src/ros_control/hardware_interface/CMakeLists.txt;31;catkin_add_gtest;/home/akingse/tempopkg_ws/src/ros_control/hardware_interface/CMakeLists.txt;0;")
add_test(_ctest_hardware_interface_gtest_actuator_state_interface_test "/home/akingse/tempopkg_ws/build_isolated/hardware_interface/catkin_generated/env_cached.sh" "/usr/bin/python2" "/opt/ros/kinetic/share/catkin/cmake/test/run_tests.py" "/home/akingse/tempopkg_ws/build_isolated/hardware_interface/test_results/hardware_interface/gtest-actuator_state_interface_test.xml" "--return-code" "/home/akingse/tempopkg_ws/devel_isolated/hardware_interface/lib/hardware_interface/actuator_state_interface_test --gtest_output=xml:/home/akingse/tempopkg_ws/build_isolated/hardware_interface/test_results/hardware_interface/gtest-actuator_state_interface_test.xml")
set_tests_properties(_ctest_hardware_interface_gtest_actuator_state_interface_test PROPERTIES  _BACKTRACE_TRIPLES "/opt/ros/kinetic/share/catkin/cmake/test/tests.cmake;160;add_test;/opt/ros/kinetic/share/catkin/cmake/test/gtest.cmake;98;catkin_run_tests_target;/opt/ros/kinetic/share/catkin/cmake/test/gtest.cmake;37;_catkin_add_google_test;/home/akingse/tempopkg_ws/src/ros_control/hardware_interface/CMakeLists.txt;34;catkin_add_gtest;/home/akingse/tempopkg_ws/src/ros_control/hardware_interface/CMakeLists.txt;0;")
add_test(_ctest_hardware_interface_gtest_actuator_command_interface_test "/home/akingse/tempopkg_ws/build_isolated/hardware_interface/catkin_generated/env_cached.sh" "/usr/bin/python2" "/opt/ros/kinetic/share/catkin/cmake/test/run_tests.py" "/home/akingse/tempopkg_ws/build_isolated/hardware_interface/test_results/hardware_interface/gtest-actuator_command_interface_test.xml" "--return-code" "/home/akingse/tempopkg_ws/devel_isolated/hardware_interface/lib/hardware_interface/actuator_command_interface_test --gtest_output=xml:/home/akingse/tempopkg_ws/build_isolated/hardware_interface/test_results/hardware_interface/gtest-actuator_command_interface_test.xml")
set_tests_properties(_ctest_hardware_interface_gtest_actuator_command_interface_test PROPERTIES  _BACKTRACE_TRIPLES "/opt/ros/kinetic/share/catkin/cmake/test/tests.cmake;160;add_test;/opt/ros/kinetic/share/catkin/cmake/test/gtest.cmake;98;catkin_run_tests_target;/opt/ros/kinetic/share/catkin/cmake/test/gtest.cmake;37;_catkin_add_google_test;/home/akingse/tempopkg_ws/src/ros_control/hardware_interface/CMakeLists.txt;37;catkin_add_gtest;/home/akingse/tempopkg_ws/src/ros_control/hardware_interface/CMakeLists.txt;0;")
add_test(_ctest_hardware_interface_gtest_joint_state_interface_test "/home/akingse/tempopkg_ws/build_isolated/hardware_interface/catkin_generated/env_cached.sh" "/usr/bin/python2" "/opt/ros/kinetic/share/catkin/cmake/test/run_tests.py" "/home/akingse/tempopkg_ws/build_isolated/hardware_interface/test_results/hardware_interface/gtest-joint_state_interface_test.xml" "--return-code" "/home/akingse/tempopkg_ws/devel_isolated/hardware_interface/lib/hardware_interface/joint_state_interface_test --gtest_output=xml:/home/akingse/tempopkg_ws/build_isolated/hardware_interface/test_results/hardware_interface/gtest-joint_state_interface_test.xml")
set_tests_properties(_ctest_hardware_interface_gtest_joint_state_interface_test PROPERTIES  _BACKTRACE_TRIPLES "/opt/ros/kinetic/share/catkin/cmake/test/tests.cmake;160;add_test;/opt/ros/kinetic/share/catkin/cmake/test/gtest.cmake;98;catkin_run_tests_target;/opt/ros/kinetic/share/catkin/cmake/test/gtest.cmake;37;_catkin_add_google_test;/home/akingse/tempopkg_ws/src/ros_control/hardware_interface/CMakeLists.txt;40;catkin_add_gtest;/home/akingse/tempopkg_ws/src/ros_control/hardware_interface/CMakeLists.txt;0;")
add_test(_ctest_hardware_interface_gtest_joint_command_interface_test "/home/akingse/tempopkg_ws/build_isolated/hardware_interface/catkin_generated/env_cached.sh" "/usr/bin/python2" "/opt/ros/kinetic/share/catkin/cmake/test/run_tests.py" "/home/akingse/tempopkg_ws/build_isolated/hardware_interface/test_results/hardware_interface/gtest-joint_command_interface_test.xml" "--return-code" "/home/akingse/tempopkg_ws/devel_isolated/hardware_interface/lib/hardware_interface/joint_command_interface_test --gtest_output=xml:/home/akingse/tempopkg_ws/build_isolated/hardware_interface/test_results/hardware_interface/gtest-joint_command_interface_test.xml")
set_tests_properties(_ctest_hardware_interface_gtest_joint_command_interface_test PROPERTIES  _BACKTRACE_TRIPLES "/opt/ros/kinetic/share/catkin/cmake/test/tests.cmake;160;add_test;/opt/ros/kinetic/share/catkin/cmake/test/gtest.cmake;98;catkin_run_tests_target;/opt/ros/kinetic/share/catkin/cmake/test/gtest.cmake;37;_catkin_add_google_test;/home/akingse/tempopkg_ws/src/ros_control/hardware_interface/CMakeLists.txt;43;catkin_add_gtest;/home/akingse/tempopkg_ws/src/ros_control/hardware_interface/CMakeLists.txt;0;")
add_test(_ctest_hardware_interface_gtest_force_torque_sensor_interface_test "/home/akingse/tempopkg_ws/build_isolated/hardware_interface/catkin_generated/env_cached.sh" "/usr/bin/python2" "/opt/ros/kinetic/share/catkin/cmake/test/run_tests.py" "/home/akingse/tempopkg_ws/build_isolated/hardware_interface/test_results/hardware_interface/gtest-force_torque_sensor_interface_test.xml" "--return-code" "/home/akingse/tempopkg_ws/devel_isolated/hardware_interface/lib/hardware_interface/force_torque_sensor_interface_test --gtest_output=xml:/home/akingse/tempopkg_ws/build_isolated/hardware_interface/test_results/hardware_interface/gtest-force_torque_sensor_interface_test.xml")
set_tests_properties(_ctest_hardware_interface_gtest_force_torque_sensor_interface_test PROPERTIES  _BACKTRACE_TRIPLES "/opt/ros/kinetic/share/catkin/cmake/test/tests.cmake;160;add_test;/opt/ros/kinetic/share/catkin/cmake/test/gtest.cmake;98;catkin_run_tests_target;/opt/ros/kinetic/share/catkin/cmake/test/gtest.cmake;37;_catkin_add_google_test;/home/akingse/tempopkg_ws/src/ros_control/hardware_interface/CMakeLists.txt;46;catkin_add_gtest;/home/akingse/tempopkg_ws/src/ros_control/hardware_interface/CMakeLists.txt;0;")
add_test(_ctest_hardware_interface_gtest_imu_sensor_interface_test "/home/akingse/tempopkg_ws/build_isolated/hardware_interface/catkin_generated/env_cached.sh" "/usr/bin/python2" "/opt/ros/kinetic/share/catkin/cmake/test/run_tests.py" "/home/akingse/tempopkg_ws/build_isolated/hardware_interface/test_results/hardware_interface/gtest-imu_sensor_interface_test.xml" "--return-code" "/home/akingse/tempopkg_ws/devel_isolated/hardware_interface/lib/hardware_interface/imu_sensor_interface_test --gtest_output=xml:/home/akingse/tempopkg_ws/build_isolated/hardware_interface/test_results/hardware_interface/gtest-imu_sensor_interface_test.xml")
set_tests_properties(_ctest_hardware_interface_gtest_imu_sensor_interface_test PROPERTIES  _BACKTRACE_TRIPLES "/opt/ros/kinetic/share/catkin/cmake/test/tests.cmake;160;add_test;/opt/ros/kinetic/share/catkin/cmake/test/gtest.cmake;98;catkin_run_tests_target;/opt/ros/kinetic/share/catkin/cmake/test/gtest.cmake;37;_catkin_add_google_test;/home/akingse/tempopkg_ws/src/ros_control/hardware_interface/CMakeLists.txt;49;catkin_add_gtest;/home/akingse/tempopkg_ws/src/ros_control/hardware_interface/CMakeLists.txt;0;")
add_test(_ctest_hardware_interface_gtest_robot_hw_test "/home/akingse/tempopkg_ws/build_isolated/hardware_interface/catkin_generated/env_cached.sh" "/usr/bin/python2" "/opt/ros/kinetic/share/catkin/cmake/test/run_tests.py" "/home/akingse/tempopkg_ws/build_isolated/hardware_interface/test_results/hardware_interface/gtest-robot_hw_test.xml" "--return-code" "/home/akingse/tempopkg_ws/devel_isolated/hardware_interface/lib/hardware_interface/robot_hw_test --gtest_output=xml:/home/akingse/tempopkg_ws/build_isolated/hardware_interface/test_results/hardware_interface/gtest-robot_hw_test.xml")
set_tests_properties(_ctest_hardware_interface_gtest_robot_hw_test PROPERTIES  _BACKTRACE_TRIPLES "/opt/ros/kinetic/share/catkin/cmake/test/tests.cmake;160;add_test;/opt/ros/kinetic/share/catkin/cmake/test/gtest.cmake;98;catkin_run_tests_target;/opt/ros/kinetic/share/catkin/cmake/test/gtest.cmake;37;_catkin_add_google_test;/home/akingse/tempopkg_ws/src/ros_control/hardware_interface/CMakeLists.txt;52;catkin_add_gtest;/home/akingse/tempopkg_ws/src/ros_control/hardware_interface/CMakeLists.txt;0;")
add_test(_ctest_hardware_interface_gtest_interface_manager_test "/home/akingse/tempopkg_ws/build_isolated/hardware_interface/catkin_generated/env_cached.sh" "/usr/bin/python2" "/opt/ros/kinetic/share/catkin/cmake/test/run_tests.py" "/home/akingse/tempopkg_ws/build_isolated/hardware_interface/test_results/hardware_interface/gtest-interface_manager_test.xml" "--return-code" "/home/akingse/tempopkg_ws/devel_isolated/hardware_interface/lib/hardware_interface/interface_manager_test --gtest_output=xml:/home/akingse/tempopkg_ws/build_isolated/hardware_interface/test_results/hardware_interface/gtest-interface_manager_test.xml")
set_tests_properties(_ctest_hardware_interface_gtest_interface_manager_test PROPERTIES  _BACKTRACE_TRIPLES "/opt/ros/kinetic/share/catkin/cmake/test/tests.cmake;160;add_test;/opt/ros/kinetic/share/catkin/cmake/test/gtest.cmake;98;catkin_run_tests_target;/opt/ros/kinetic/share/catkin/cmake/test/gtest.cmake;37;_catkin_add_google_test;/home/akingse/tempopkg_ws/src/ros_control/hardware_interface/CMakeLists.txt;55;catkin_add_gtest;/home/akingse/tempopkg_ws/src/ros_control/hardware_interface/CMakeLists.txt;0;")
add_test(_ctest_hardware_interface_gtest_posvel_command_interface_test "/home/akingse/tempopkg_ws/build_isolated/hardware_interface/catkin_generated/env_cached.sh" "/usr/bin/python2" "/opt/ros/kinetic/share/catkin/cmake/test/run_tests.py" "/home/akingse/tempopkg_ws/build_isolated/hardware_interface/test_results/hardware_interface/gtest-posvel_command_interface_test.xml" "--return-code" "/home/akingse/tempopkg_ws/devel_isolated/hardware_interface/lib/hardware_interface/posvel_command_interface_test --gtest_output=xml:/home/akingse/tempopkg_ws/build_isolated/hardware_interface/test_results/hardware_interface/gtest-posvel_command_interface_test.xml")
set_tests_properties(_ctest_hardware_interface_gtest_posvel_command_interface_test PROPERTIES  _BACKTRACE_TRIPLES "/opt/ros/kinetic/share/catkin/cmake/test/tests.cmake;160;add_test;/opt/ros/kinetic/share/catkin/cmake/test/gtest.cmake;98;catkin_run_tests_target;/opt/ros/kinetic/share/catkin/cmake/test/gtest.cmake;37;_catkin_add_google_test;/home/akingse/tempopkg_ws/src/ros_control/hardware_interface/CMakeLists.txt;58;catkin_add_gtest;/home/akingse/tempopkg_ws/src/ros_control/hardware_interface/CMakeLists.txt;0;")
add_test(_ctest_hardware_interface_gtest_posvelacc_command_interface_test "/home/akingse/tempopkg_ws/build_isolated/hardware_interface/catkin_generated/env_cached.sh" "/usr/bin/python2" "/opt/ros/kinetic/share/catkin/cmake/test/run_tests.py" "/home/akingse/tempopkg_ws/build_isolated/hardware_interface/test_results/hardware_interface/gtest-posvelacc_command_interface_test.xml" "--return-code" "/home/akingse/tempopkg_ws/devel_isolated/hardware_interface/lib/hardware_interface/posvelacc_command_interface_test --gtest_output=xml:/home/akingse/tempopkg_ws/build_isolated/hardware_interface/test_results/hardware_interface/gtest-posvelacc_command_interface_test.xml")
set_tests_properties(_ctest_hardware_interface_gtest_posvelacc_command_interface_test PROPERTIES  _BACKTRACE_TRIPLES "/opt/ros/kinetic/share/catkin/cmake/test/tests.cmake;160;add_test;/opt/ros/kinetic/share/catkin/cmake/test/gtest.cmake;98;catkin_run_tests_target;/opt/ros/kinetic/share/catkin/cmake/test/gtest.cmake;37;_catkin_add_google_test;/home/akingse/tempopkg_ws/src/ros_control/hardware_interface/CMakeLists.txt;61;catkin_add_gtest;/home/akingse/tempopkg_ws/src/ros_control/hardware_interface/CMakeLists.txt;0;")
subdirs("gtest")
