set(_CATKIN_CURRENT_PACKAGE "rqt_controller_manager")
set(rqt_controller_manager_VERSION "0.19.4")
set(rqt_controller_manager_MAINTAINER "Bence Magyar <bence.magyar.robotics@gmail.com>, Enrique Fernandez <enrique.fernandez.perdomo@gmail.com>, Mathias Lüdtke <mathias.luedtke@ipa.fraunhofer.de>")
set(rqt_controller_manager_PACKAGE_FORMAT "3")
set(rqt_controller_manager_BUILD_DEPENDS )
set(rqt_controller_manager_BUILD_EXPORT_DEPENDS )
set(rqt_controller_manager_BUILDTOOL_DEPENDS "catkin" "python-setuptools" "python3-setuptools")
set(rqt_controller_manager_BUILDTOOL_EXPORT_DEPENDS )
set(rqt_controller_manager_EXEC_DEPENDS "controller_manager_msgs" "rospy" "rqt_gui" "rqt_gui_py")
set(rqt_controller_manager_RUN_DEPENDS "controller_manager_msgs" "rospy" "rqt_gui" "rqt_gui_py")
set(rqt_controller_manager_TEST_DEPENDS )
set(rqt_controller_manager_DOC_DEPENDS )
set(rqt_controller_manager_URL_WEBSITE "http://ros.org/wiki/rqt_controller_manager")
set(rqt_controller_manager_URL_BUGTRACKER "https://github.com/ros-controls/ros_control/issues")
set(rqt_controller_manager_URL_REPOSITORY "https://github.com/ros-controls/ros_control")
set(rqt_controller_manager_DEPRECATED "")