set(rqt_controller_manager_SETUP_PY_SETUP_MODULE "setuptools")
set(rqt_controller_manager_SETUP_PY_VERSION "0.19.4")
set(rqt_controller_manager_SETUP_PY_SCRIPTS "")
set(rqt_controller_manager_SETUP_PY_PACKAGES "rqt_controller_manager")
set(rqt_controller_manager_SETUP_PY_PACKAGE_DIRS "src/rqt_controller_manager")
set(rqt_controller_manager_SETUP_PY_MODULES "")
set(rqt_controller_manager_SETUP_PY_MODULE_DIRS "")