set(_CATKIN_CURRENT_PACKAGE "diff_drive_controller")
set(diff_drive_controller_VERSION "0.18.1")
set(diff_drive_controller_MAINTAINER "Bence Magyar <bence.magyar.robotics@gmail.com>, Enrique Fernandez <enrique.fernandez.perdomo@gmail.com>")
set(diff_drive_controller_PACKAGE_FORMAT "3")
set(diff_drive_controller_BUILD_DEPENDS "boost" "pluginlib" "urdf" "controller_interface" "control_msgs" "dynamic_reconfigure" "geometry_msgs" "hardware_interface" "nav_msgs" "realtime_tools" "tf")
set(diff_drive_controller_BUILD_EXPORT_DEPENDS "boost" "controller_interface" "control_msgs" "dynamic_reconfigure" "geometry_msgs" "hardware_interface" "nav_msgs" "realtime_tools" "tf")
set(diff_drive_controller_BUILDTOOL_DEPENDS "catkin")
set(diff_drive_controller_BUILDTOOL_EXPORT_DEPENDS )
set(diff_drive_controller_EXEC_DEPENDS "pluginlib" "urdf" "controller_interface" "control_msgs" "dynamic_reconfigure" "geometry_msgs" "hardware_interface" "nav_msgs" "realtime_tools" "tf")
set(diff_drive_controller_RUN_DEPENDS "pluginlib" "urdf" "controller_interface" "control_msgs" "dynamic_reconfigure" "geometry_msgs" "hardware_interface" "nav_msgs" "realtime_tools" "tf" "boost")
set(diff_drive_controller_TEST_DEPENDS "controller_manager" "rosgraph_msgs" "rostest" "rostopic" "std_srvs" "xacro")
set(diff_drive_controller_DOC_DEPENDS )
set(diff_drive_controller_URL_WEBSITE "https://github.com/ros-controls/ros_controllers/wiki")
set(diff_drive_controller_URL_BUGTRACKER "https://github.com/ros-controls/ros_controllers/issues")
set(diff_drive_controller_URL_REPOSITORY "https://github.com/ros-controls/ros_controllers")
set(diff_drive_controller_DEPRECATED "")