set(_CATKIN_CURRENT_PACKAGE "controller_interface")
set(controller_interface_VERSION "0.19.4")
set(controller_interface_MAINTAINER "Bence Magyar <bence.magyar.robotics@gmail.com>, Enrique Fernandez <enrique.fernandez.perdomo@gmail.com>, Mathias Lüdtke <mathias.luedtke@ipa.fraunhofer.de>")
set(controller_interface_PACKAGE_FORMAT "3")
set(controller_interface_BUILD_DEPENDS "hardware_interface" "roscpp")
set(controller_interface_BUILD_EXPORT_DEPENDS "hardware_interface" "roscpp")
set(controller_interface_BUILDTOOL_DEPENDS "catkin")
set(controller_interface_BUILDTOOL_EXPORT_DEPENDS )
set(controller_interface_EXEC_DEPENDS "roscpp")
set(controller_interface_RUN_DEPENDS "roscpp" "hardware_interface")
set(controller_interface_TEST_DEPENDS )
set(controller_interface_DOC_DEPENDS )
set(controller_interface_URL_WEBSITE "https://github.com/ros-controls/ros_control/wiki")
set(controller_interface_URL_BUGTRACKER "https://github.com/ros-controls/ros_control/issues")
set(controller_interface_URL_REPOSITORY "https://github.com/ros-controls/ros_control")
set(controller_interface_DEPRECATED "")