# CMake generated Testfile for 
# Source directory: /home/akingse/tempopkg_ws/src/velodyne/velodyne_laserscan/tests
# Build directory: /home/akingse/tempopkg_ws/build_isolated/velodyne_laserscan/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(_ctest_velodyne_laserscan_rostest_tests_lazy_subscriber_node.test "/home/akingse/tempopkg_ws/build_isolated/velodyne_laserscan/catkin_generated/env_cached.sh" "/usr/bin/python2" "/opt/ros/kinetic/share/catkin/cmake/test/run_tests.py" "/home/akingse/tempopkg_ws/build_isolated/velodyne_laserscan/test_results/velodyne_laserscan/rostest-tests_lazy_subscriber_node.xml" "--return-code" "/opt/ros/kinetic/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/akingse/tempopkg_ws/src/velodyne/velodyne_laserscan --package=velodyne_laserscan --results-filename tests_lazy_subscriber_node.xml --results-base-dir \"/home/akingse/tempopkg_ws/build_isolated/velodyne_laserscan/test_results\" /home/akingse/tempopkg_ws/src/velodyne/velodyne_laserscan/tests/lazy_subscriber_node.test ")
set_tests_properties(_ctest_velodyne_laserscan_rostest_tests_lazy_subscriber_node.test PROPERTIES  _BACKTRACE_TRIPLES "/opt/ros/kinetic/share/catkin/cmake/test/tests.cmake;160;add_test;/opt/ros/kinetic/share/rostest/cmake/rostest-extras.cmake;52;catkin_run_tests_target;/opt/ros/kinetic/share/rostest/cmake/rostest-extras.cmake;80;add_rostest;/opt/ros/kinetic/share/rostest/cmake/rostest-extras.cmake;100;_add_rostest_google_test;/home/akingse/tempopkg_ws/src/velodyne/velodyne_laserscan/tests/CMakeLists.txt;15;add_rostest_gtest;/home/akingse/tempopkg_ws/src/velodyne/velodyne_laserscan/tests/CMakeLists.txt;0;")
add_test(_ctest_velodyne_laserscan_rostest_tests_lazy_subscriber_nodelet.test "/home/akingse/tempopkg_ws/build_isolated/velodyne_laserscan/catkin_generated/env_cached.sh" "/usr/bin/python2" "/opt/ros/kinetic/share/catkin/cmake/test/run_tests.py" "/home/akingse/tempopkg_ws/build_isolated/velodyne_laserscan/test_results/velodyne_laserscan/rostest-tests_lazy_subscriber_nodelet.xml" "--return-code" "/opt/ros/kinetic/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/akingse/tempopkg_ws/src/velodyne/velodyne_laserscan --package=velodyne_laserscan --results-filename tests_lazy_subscriber_nodelet.xml --results-base-dir \"/home/akingse/tempopkg_ws/build_isolated/velodyne_laserscan/test_results\" /home/akingse/tempopkg_ws/src/velodyne/velodyne_laserscan/tests/lazy_subscriber_nodelet.test ")
set_tests_properties(_ctest_velodyne_laserscan_rostest_tests_lazy_subscriber_nodelet.test PROPERTIES  _BACKTRACE_TRIPLES "/opt/ros/kinetic/share/catkin/cmake/test/tests.cmake;160;add_test;/opt/ros/kinetic/share/rostest/cmake/rostest-extras.cmake;52;catkin_run_tests_target;/opt/ros/kinetic/share/rostest/cmake/rostest-extras.cmake;80;add_rostest;/opt/ros/kinetic/share/rostest/cmake/rostest-extras.cmake;100;_add_rostest_google_test;/home/akingse/tempopkg_ws/src/velodyne/velodyne_laserscan/tests/CMakeLists.txt;19;add_rostest_gtest;/home/akingse/tempopkg_ws/src/velodyne/velodyne_laserscan/tests/CMakeLists.txt;0;")
add_test(_ctest_velodyne_laserscan_rostest_tests_system_node.test "/home/akingse/tempopkg_ws/build_isolated/velodyne_laserscan/catkin_generated/env_cached.sh" "/usr/bin/python2" "/opt/ros/kinetic/share/catkin/cmake/test/run_tests.py" "/home/akingse/tempopkg_ws/build_isolated/velodyne_laserscan/test_results/velodyne_laserscan/rostest-tests_system_node.xml" "--return-code" "/opt/ros/kinetic/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/akingse/tempopkg_ws/src/velodyne/velodyne_laserscan --package=velodyne_laserscan --results-filename tests_system_node.xml --results-base-dir \"/home/akingse/tempopkg_ws/build_isolated/velodyne_laserscan/test_results\" /home/akingse/tempopkg_ws/src/velodyne/velodyne_laserscan/tests/system_node.test ")
set_tests_properties(_ctest_velodyne_laserscan_rostest_tests_system_node.test PROPERTIES  _BACKTRACE_TRIPLES "/opt/ros/kinetic/share/catkin/cmake/test/tests.cmake;160;add_test;/opt/ros/kinetic/share/rostest/cmake/rostest-extras.cmake;52;catkin_run_tests_target;/opt/ros/kinetic/share/rostest/cmake/rostest-extras.cmake;80;add_rostest;/opt/ros/kinetic/share/rostest/cmake/rostest-extras.cmake;100;_add_rostest_google_test;/home/akingse/tempopkg_ws/src/velodyne/velodyne_laserscan/tests/CMakeLists.txt;23;add_rostest_gtest;/home/akingse/tempopkg_ws/src/velodyne/velodyne_laserscan/tests/CMakeLists.txt;0;")
add_test(_ctest_velodyne_laserscan_rostest_tests_system_nodelet.test "/home/akingse/tempopkg_ws/build_isolated/velodyne_laserscan/catkin_generated/env_cached.sh" "/usr/bin/python2" "/opt/ros/kinetic/share/catkin/cmake/test/run_tests.py" "/home/akingse/tempopkg_ws/build_isolated/velodyne_laserscan/test_results/velodyne_laserscan/rostest-tests_system_nodelet.xml" "--return-code" "/opt/ros/kinetic/share/rostest/cmake/../../../bin/rostest --pkgdir=/home/akingse/tempopkg_ws/src/velodyne/velodyne_laserscan --package=velodyne_laserscan --results-filename tests_system_nodelet.xml --results-base-dir \"/home/akingse/tempopkg_ws/build_isolated/velodyne_laserscan/test_results\" /home/akingse/tempopkg_ws/src/velodyne/velodyne_laserscan/tests/system_nodelet.test ")
set_tests_properties(_ctest_velodyne_laserscan_rostest_tests_system_nodelet.test PROPERTIES  _BACKTRACE_TRIPLES "/opt/ros/kinetic/share/catkin/cmake/test/tests.cmake;160;add_test;/opt/ros/kinetic/share/rostest/cmake/rostest-extras.cmake;52;catkin_run_tests_target;/opt/ros/kinetic/share/rostest/cmake/rostest-extras.cmake;80;add_rostest;/opt/ros/kinetic/share/rostest/cmake/rostest-extras.cmake;100;_add_rostest_google_test;/home/akingse/tempopkg_ws/src/velodyne/velodyne_laserscan/tests/CMakeLists.txt;27;add_rostest_gtest;/home/akingse/tempopkg_ws/src/velodyne/velodyne_laserscan/tests/CMakeLists.txt;0;")
